### ISSUE TITLE
Please update the program

### ISSUE THREAD

**Issue by Elonnuir** [Tenza/SteamKalix#2]
Good afternoon! I'm new to programming so I can not figure out your code. Help me please. Can you change the program? Now Steam does not use Steam to enter Steam, the code needs to use the Mobile Steam Authenticator, I do not need to write an authenticator, I use it https://github.com/Jessecar96/SteamDesktopAuthenticator
I tried to launch your program 
Warning: QSslSocket: cannot call unresolved function SSLv23_client_method (ssl\qsslsocket_openssl_symbols.cpp:125, void __cdecl `anonymous-namespace'::qsslSocketUnresolvedSymbolWarning(const char *))
Warning: QSslSocket: cannot call unresolved function SSL_CTX_new (ssl\qsslsocket_openssl_symbols.cpp:125, void __cdecl `anonymous-namespace'::qsslSocketUnresolvedSymbolWarning(const char *))
Warning: QSslSocket: cannot call unresolved function SSL_library_init (ssl\qsslsocket_openssl_symbols.cpp:125, void __cdecl `anonymous-namespace'::qsslSocketUnresolvedSymbolWarning(const char *))
Warning: QSslSocket: cannot call unresolved function ERR_get_error (ssl\qsslsocket_openssl_symbols.cpp:125, void __cdecl `anonymous-namespace'::qsslSocketUnresolvedSymbolWarning(const char *))
Warning: QSslSocket: cannot call unresolved function ERR_get_error (ssl\qsslsocket_openssl_symbols.cpp:125, void __cdecl `anonymous-namespace'::qsslSocketUnresolvedSymbolWarning(const char *))

**Comment by Tenza** [comment]
Hi there, I'm sorry for taking so long. 

The code available is supposed to work, but it is not complete as it goes against the TOS of steam. I will later checkout the error you described.

**Comment by Elonnuir** [comment]
Good day! Since 2014, a lot has changed in Steam, to be precise, the confirmation via e-mail has been replaced with a mobile application that constantly generates new keys, as well as canceled the captcha - so the application can not work now.
I am an amateur programmer, but I still managed to change your program to make it work.
You write programs to order, do I need something?

**Comment by Tenza** [comment]
Hello! That's great that you are able to make it work! I'm away from steam now, and unfortunately I did not know they made so many changes to the authentication. 

Yes, I wrote the program to monitor specific items, and it would calculate a good price to buy and sell items for you. At the time there was no "Order" system, so the extra code that I wrote was only supporting the legacy buying system.
